AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 3 API -  com.fse.blogsite::java-lambda
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  JavaLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.fse.blogsite.LambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment:
        Variables:
          MONGO_URI: "mongodb://127.0.0.1:27017/admin"
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

